from fastai.vision.all import *
import gradio as gr
import requests
import json

# URL = 'https://dog.ceo/api/breeds/list/all'

# result = requests.get(url = URL).json()
searchText = ['affenpinscher',
 'african',
 'airedale',
 'akita',
 'appenzeller',
 'shepherd australian',
 'basenji',
 'beagle',
 'bluetick',
 'borzoi',
 'bouvier',
 'boxer',
 'brabancon',
 'briard',
 'norwegian buhund',
 'boston bulldog',
 'english bulldog',
 'french bulldog',
 'staffordshire bullterrier',
 'australian cattledog',
 'chihuahua',
 'chow',
 'clumber',
 'cockapoo',
 'border collie',
 'coonhound',
 'cardigan corgi',
 'cotondetulear',
 'dachshund',
 'dalmatian',
 'great dane',
 'scottish deerhound',
 'dhole',
 'dingo',
 'doberman',
 'norwegian elkhound',
 'entlebucher',
 'eskimo',
 'lapphund finnish',
 'bichon frise',
 'germanshepherd',
 'italian greyhound',
 'groenendael',
 'havanese',
 'afghan hound',
 'basset hound',
 'blood hound',
 'english hound',
 'ibizan hound',
 'plott hound',
 'walker hound',
 'husky',
 'keeshond',
 'kelpie',
 'komondor',
 'kuvasz',
 'labradoodle',
 'labrador',
 'leonberg',
 'lhasa',
 'malamute',
 'malinois',
 'maltese',
 'bull mastiff',
 'english mastiff',
 'tibetan mastiff',
 'mexicanhairless',
 'mix',
 'bernese mountain',
 'swiss mountain',
 'newfoundland',
 'otterhound',
 'caucasian ovcharka',
 'papillon',
 'pekinese',
 'pembroke',
 'miniature pinscher',
 'pitbull',
 'german pointer',
 'germanlonghair pointer',
 'pomeranian',
 'medium poodle',
 'miniature poodle',
 'standard poodle',
 'toy poodle',
 'pug',
 'puggle',
 'pyrenees',
 'redbone',
 'chesapeake retriever',
 'curly retriever',
 'flatcoated retriever',
 'golden retriever',
 'rhodesian ridgeback',
 'rottweiler',
 'saluki',
 'samoyed',
 'schipperke',
 'giant schnauzer',
 'miniature schnauzer',
 'english setter',
 'gordon setter',
 'irish setter',
 'sharpei',
 'english sheepdog',
 'shetland sheepdog',
 'shiba',
 'shihtzu',
 'blenheim spaniel',
 'brittany spaniel',
 'cocker spaniel',
 'irish spaniel',
 'japanese spaniel',
 'sussex spaniel',
 'welsh spaniel',
 'english springer',
 'stbernard',
 'american terrier',
 'australian terrier',
 'bedlington terrier',
 'border terrier',
 'cairn terrier',
 'dandie terrier',
 'fox terrier',
 'irish terrier',
 'kerryblue terrier',
 'lakeland terrier',
 'norfolk terrier',
 'norwich terrier',
 'patterdale terrier',
 'russell terrier',
 'scottish terrier',
 'sealyham terrier',
 'silky terrier',
 'tibetan terrier',
 'toy terrier',
 'welsh terrier',
 'westhighland terrier',
 'wheaten terrier',
 'yorkshire terrier',
 'tervuren',
 'vizsla',
 'spanish waterdog',
 'weimaraner',
 'whippet',
 'irish wolfhound']

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(searchText, map(float, probs)))

learn = load_learner('dogIdentifierModel.pkl')

image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['golden-retriever.jpg', 'german-shepherd.jpg', 'pinscher.jpg', 'husky.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)